`timescale 1ns / 1ps
//Module for Store instructions - data to be written to reg file is generated by this module
module L_type(
    input [31:0] instr,
    input [31:0] daddr,
    input [31:0] drdata,
    output reg[31:0] out
);
    
	 reg [31:0] offset;
    always@(instr or daddr or drdata)
    begin   
        offset = (daddr[1:0]<<3);  //offset = 8*rv1[1:0]-1 ,eg, 8*1=8, so drdata[15:8]
        case(instr[14:12])
        3'b000: out = {{24{drdata[offset+7]}}, drdata[offset +: 8]};    //LB
        3'b001: out = {{16{drdata[offset+15]}}, drdata[offset +: 16]};  //LH
        3'b010: out = drdata;                                   			//LW
        3'b100: out = {24'b0, drdata[offset +: 8]};             			//LBU
        3'b101: out = {16'b0, drdata[offset +: 16]};            			//LHU
        endcase
    end
endmodule