`timescale 1ns / 1ps
//Module for Store instructions - we signal is generated by this module
module S_type(
    input [31:0] instr,
    input [31:0] daddr,
    output reg[3:0] we
);
    always@(instr or daddr)
    begin   
        case(instr[14:12])
        3'b000: we = (4'b0001)<<daddr[1:0];     //SB
        3'b001: we = (4'b0011)<<daddr[1:0];     //SH
        3'b010: we = 4'b1111;                   //SW
        endcase
    end
endmodule